### ISSUE TITLE
question about the initialization of teacher model

### ISSUE THREAD

**Issue by dazhangyu123** [DearCaat/MHIM-MIL#1]
I am reimplementing your method on a new dataset and want to know how to get the initialization checkpoint of the teacher model.

**Comment by DearCaat** [comment]
just regular training but the random seed should be matched, e.g., baseline: `transmil`, seed: `2021`: 
`python3 main.py --project=$PROJECT_NAME --dataset_root=$DATASET_PATH --model_path=$OUTPUT_PATH --cv_fold=3 --title=transmil --model=transmil --seed=2021`

**Comment by akidway** [comment]
Hi, @DearCaat
Can I directly use baseline dsmil weight as teacher_init for dsmil mhim (same random seed)?
From your code, I found only one difference between baseline dsmil and dsmil for mhim is dsmil for mhim in i_classifier miss a nn.drop().
