### ISSUE TITLE
seed setting

### ISSUE THREAD

**Issue by lingxitong** [DearCaat/MHIM-MIL#10]
in your paper ,I see you rerun 3 times and report the std and mean value,that is good use to avoid random ans,But I have a quest,should the dataset split by seed ,such as you use seed 2021 2022 2023 to run three times ,the dataset split in the three times is different or same?can you tell me which is good? thanks

**Comment by DearCaat** [comment]
The [seed setting in the code](https://github.com/DearCaat/MHIM-MIL/blob/master/utils.py#L6) changes all packages and python3's random seed. Therefore, the data split is different on all 3 times. 
I can't say for sure which one is optimal, but I personally think this allows me to evaluate the performance of the model with different data splits.

**Comment by lingxitong** [comment]
thanks
