### ISSUE TITLE
根据自己的数据集，teacher初始化权重问题，出现"Missing keys & unexpected keys

### ISSUE THREAD

**Issue by LiQun66** [DearCaat/MHIM-MIL#15]
1、python3 main.py --project=$PROJECT_NAME --dataset_root=$DATASET_PATH --model_path=$OUTPUT_PATH --cv_fold=3 --title=transmil --model=pure --baseline=selfattn --seed=2021我适用了这个命令行生成了fold_0_model_best_auc.pt，fold_1_model_best_auc.pt，fold_2_model_best_auc.pt文件，来作为teacher_init的输入。
2、Python3 main.py --project=$PROJECT_NAME --dataset_root=$DATASET_PATH --model_path=$OUTPUT_PATH --cv_fold=3 \
--teacher_init=第1步生成的pt文件 --mask_ratio_h=0.03 --mask_ratio_hr=0.5 \
--mrh_sche --title=transmil_mhim --mask_ratio=0. --mask_ratio_l=0.8 --cl_alpha=0.1 --mm_sche --init_stu_type=fc --attn_layer=0 --seed=2021（采用的是mhim模型，baseline为selfattn）
3、出现"Missing keys & unexpected keys，显示第1步生成的模型的key只有model和teacher,然后我查看第1步的ckp.pt文件有以下key：model
lr_sche
optimizer
epoch
k
early_stop
random
ckc_metric
val_best_metric
te_best_metric
wandb_id
而模型期待的两个key
patch_to_emb.0.weight
patch_to_emb.0.bias
却没有，请问作者我是不是哪一步出错了？

**Comment by DearCaat** [comment]
非常感谢你对我们工作的关注！
也非常抱歉因为我个人代码的问题对你工作造成的不便，这个问题是因为代码版本的问题
实际上就是保存下来的`.pt`文件中的`model`字段包含期待的key。我已经在最新的[Github仓库](https://github.com/DearCaat/MHIM-MIL/blob/master/main.py)中修复了这个问题，添加了以下代码，详情见[commit](https://github.com/DearCaat/MHIM-MIL/commit/745e5b18ab9c77472ae9e0da32ff948d0e62c163)。

```
if 'model' in pre_dict:
    pre_dict = pre_dict['model']
```
如果你后续还有问题，欢迎再次留言！
