### ISSUE TITLE
about dsmil code

### ISSUE THREAD

**Issue by akidway** [DearCaat/MHIM-MIL#16]
Hi, @DearCaat 

Thank you for you nice job.

I have a little question about your code of dsmil. 
In [your code](https://github.com/DearCaat/MHIM-MIL/blob/master/modules/dsmil.py#L23), class FCLayer use an activation function such as gelu or relu, while in [official dsmil code](https://github.com/binli123/dsmil-wsi/blob/master/dsmil.py#L9), there is no activation function in FCLayer.

Will this nonlinear lead a better result than it actually is.

I wonder if you could share some of your views.

**Comment by DearCaat** [comment]
Hi, thanks for attention!

In fact, all of the comparison methods (including DSMIL) that appear in the paper are reproduced by code from this repository.
So, you can see all the reproduced methods include an activation function in the FCLayer. I think these are fair.

Moreover, u can drop the activation function in the FCLayer. It will have an effect on the final performance, but this effect is present for all methods.

**Comment by akidway** [comment]
Thank you for reply.
Best wishes.

**Comment by DearCaat** [comment]
> Thank you for reply. Best wishes.

Best wishes!
