### ISSUE TITLE
.json file for segmentation annotation on camelyon16 in vis.ipynb

### ISSUE THREAD

**Issue by Hyun1A** [DearCaat/MHIM-MIL#17]
Thank you for you great work. I want to visualize the results of MHIM-MIL through vis.ipynb, but I couldn't find json files required to run the notebook. It would be very helpful sharing the .json files for WSIs.

**Comment by DearCaat** [comment]
Hi, thanks for attention.
This [link](https://pan.baidu.com/s/1mSzLJ_RVCJFQGe2lZAvEUA?pwd=2024) updated the segmentation mask of C16 tumor slides. 
Pls to check it.

**Comment by Hyun1A** [comment]
The issue has been resolved. Thank you!
