### ISSUE TITLE
Docker loadError

### ISSUE THREAD

**Issue by BUPT-BownZ** [DearCaat/MHIM-MIL#19]
I encountered the problem ”open /home/user/docker/tmp/docker-import-2333838786/boot/json: no such file or directory'“，when trying to load the Docker environment. After checking the cause, I found that it might be due to an incomplete Docker tar file. Have you ever encountered this issue? Could you please update the Docker image tar file again?

**Comment by DearCaat** [comment]
Pls try to `docker import` to use the Docker image.
After that, if u have more question, feel free to comment here.

**Comment by BUPT-BownZ** [comment]
After creating the Docker container, I attempted to execute:
> bash
> python3 main.py --project=$PROJECT_NAME --dataset_root=$DATASET_PATH --model_path=$OUTPUT_PATH --cv_fold=3 --title=transmil --model=pure --baseline=selfattn --seed=2021

 However, an error occurred:

Traceback (most recent call last):
> File "main.py", line 807, in <module>
>     os.mkdir(os.path.join(args.model_path, args.project))
> FileNotFoundError: [Errno 2] No such file or directory: ''

The cause of this error is that the variable in --project=$PROJECT_NAME needs to be defined by the user. The question is whether this issue is due to the Docker environment not being configured properly?

**Comment by DearCaat** [comment]
No, this has nothing to do with the environment, this should be your custom variable.
