### ISSUE TITLE
dsmil doesn't work

### ISSUE THREAD

**Issue by Daisymiaomiaomiao** [DearCaat/MHIM-MIL#21]
Hi, thank you for your nice work.
I have a little question about the code of dsmil.

for the same FEATURE files (.pt .h5 and label.csv), it will work in ABMIL 
python3 main.py  --dataset_root=$DATASET_PATH --model_path=$OUTPUT_PATH --cv_fold=3 --title=abmil --model=pure --baseline=attn --seed=2021

but doesn't work in DSMIL:
python3 main.py --dataset_root=$DATASET_PATH --model_path=$OUTPUT_PATH --cv_fold=3 --title=dsmil --model=pure --baseline=dsmil --seed=2021

it shows:
Traceback (most recent call last):
  File "main.py", line 847, in <module>
    main(args=args)
  File "main.py", line 66, in main
    ckc_metric = one_fold(args,k,ckc_metric,train_p, train_l, test_p, test_l,val_p,val_l)
  File "main.py", line 295, in one_fold
    train_loss,start,end = train_loop(args,model,model_tea,train_loader,optimizer,device,amp_autocast,criterion,loss_scaler,scheduler,k,mm_sche,epoch)
  File "main.py", line 528, in train_loop
    train_logits, cls_loss,patch_num,keep_num = model.pure(bag)
  File "/home/jun/MHIM-MIL-master/modules/mhim.py", line 214, in pure
    x = self.predictor(x)
  File "/home/jun/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jun/.local/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
**TypeError: linear(): argument 'input' (position 1) must be Tensor, not tuple**

could you help me? Thanks in advance.

**Comment by DearCaat** [comment]
Sorry, I found some bugs in this current version of the code regarding the DSMIL. I will fix it in the next couple of days, sorry again.

**Comment by DearCaat** [comment]
> Sorry, I found some bugs in this current version of the code regarding the DSMIL. I will fix it in the next couple of days, sorry again.

I have uploaded the [modified code](https://github.com/DearCaat/MHIM-MIL/commit/ecba774765f9c850153ac00ec83a78f97954df31), but I currently do not have a GPU environment to test the feasibility of the uploaded code. If there are any issues with the code, please leave a message here. Thank you very much!

**Comment by Daisymiaomiaomiao** [comment]
Thank you so much. I can run DSMIL now.
there are three more errors.

two  in main.py:
` args.backbone == 'dsmil'    `
shoule be 
`args.baseline == 'dsmil'`

another is in utils.py
`def five_scores()`
should return accuracy, auc_value, precision, recall, fscore, **threshold_optimal**

I really appreciate that you fix DSMIL code in just several hours. Thank you so much

**Comment by DearCaat** [comment]
Thank you very much for your feedback and best of success with your research!
