### ISSUE TITLE
EarlyStop for C16

### ISSUE THREAD

**Issue by HHHedo** [DearCaat/MHIM-MIL#4]
Hi,
Thanks for your great work.
I have a question about the setting of the early stop in Camelyon16. Is there any validation set in the 3-fold CV?

Thanks!

**Comment by DearCaat** [comment]
Hello, thanks for attention
EarlyStop for C16: max epoch: 200, stop epoch: 120, patience: 30, [code](https://github.com/DearCaat/MHIM-MIL/blob/master/main.py#L257).
Validation in C16: **No**, cause the count of slides in C16 is so limited (there are only 398 in total, and only ~20 slides will be used for validation).

**Comment by HHHedo** [comment]
> Hello, thanks for attention EarlyStop for C16: max epoch: 200, stop epoch: 120, patience: 30, [code](https://github.com/DearCaat/MHIM-MIL/blob/master/main.py#L257). Validation in C16: **No**, cause the count of slides in C16 is so limited (there are only 398 in total, and only ~20 slides will be used for validation).

Thanks for your quick response. 
Since no validation set is used, which metric will the EarlyStop depend on?

**Comment by DearCaat** [comment]
Just the test set, see [codes](https://github.com/DearCaat/MHIM-MIL/blob/master/main.py#L111). This is common in survival prediction tasks [1], also due to the small number of samples.
[1] Multimodal Co-Attention Transformer for Survival Prediction in Gigapixel Whole Slide Images. ICCV 2021
