### ISSUE TITLE
How to preprocess the cam16 dataset?

### ISSUE THREAD

**Issue by weiaicunzai** [DearCaat/MHIM-MIL#5]
Hi, thanks for your great work,  could you please tell me how do you preprocessed cam16 dataset?
 
In the paper, I have noticed that you claim to use CLAM api to extract patch features. However, CLAM api does not perform well on cam16  dataset. 

For example, I have stored the segmentation mask of CLAM api (default parameters), and for normal_027 slide, it gives zero tissue region:
![normal_027](https://github.com/DearCaat/MHIM-MIL/assets/1770114/dae5ee03-ad80-4c41-8a3e-f2b6c3e82c06)

So could please tell me how do you segment the tissue areas and extracting patch level features? Did you use this [code](https://github.com/DearCaat/MHIM-MIL/blob/master/DTFD/Patch_Generation/gen_patch_noLabel_stride_MultiProcessing_multiScales.py)?

**Comment by DearCaat** [comment]
Hi, thanks for attention.
This [code](https://github.com/DearCaat/MHIM-MIL?tab=readme-ov-file#patching) and parameters are used to preprocess the cam16:
`python create_patches_fp.py --source DATA_DIRECTORY --save_dir RESULTS_DIRECTORY --patch_size 512 --step_size 512 --preset bwh_biopsy.csv --seg --patch`.
This is the segmented image for normal_027:
![normal_027](https://github.com/DearCaat/MHIM-MIL/assets/33518172/2cea4e0c-ebcd-4377-825c-8b79a848c071)
I hope this will address your issue.

**Comment by weiaicunzai** [comment]
> I hope this will address your issue.

Thanks, guess I have forgot to add `bwh_biopsy.csv` parameters in the command.
After adding the `bwh_biopsy.csv` parameters,  here is what I got:
![image](https://github.com/DearCaat/MHIM-MIL/assets/1770114/778f36e5-16f6-4061-bcdb-37e6cfdaf6fc)


I didn't even noticed this parameters, I thought something wrong with the CLAM api, so I wrote my  own function to segment the tissue areas, gives me something like this. I guess my code is not as good as the CLAM api. I have wasted too many time  on this.
![image](https://github.com/DearCaat/MHIM-MIL/assets/1770114/ac270f49-0d4a-425e-82b8-1915d29f4341)


Another follow-up question:
I have noticed that you extract images from 40x magnification with patch size 512 x 512 on cam16 dataset.  I'm assuming you will resize the 512x512  to 256x256  before sending to the network  to extract patch features  Why  not just directly extracting the 256x256 features from 20x magnification like many other works would do?  Does extracting patches from 512x512 at 40x mag gives more performance boost? 

Thank you very much, you really help me a lot.

**Comment by DearCaat** [comment]
> > I hope this will address your issue.
> 
> Thanks, guess I have forgot to add `bwh_biopsy.csv` parameters in the command. After adding the `bwh_biopsy.csv` parameter, here is what I got: ![image](https://private-user-images.githubusercontent.com/1770114/294743723-778f36e5-16f6-4061-bcdb-37e6cfdaf6fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTQxODMsIm5iZiI6MTcwNDYxMzg4MywicGF0aCI6Ii8xNzcwMTE0LzI5NDc0MzcyMy03NzhmMzZlNS0xNmY2LTQwNjEtYmNkYi0zN2U2Y2ZkYWY2ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDdUMDc1MTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWI2M2RmMTdiOWM1ZTQyZmQ4ODM0Y2YzMmE4ZGQ4ZmI2MGI5YzM5YmI0YjEzYWY1OGZjYjM0NTI3MzlhMWE5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r3odT6IC_VGenJnSZCtH2Rig0jKE87aLYm4Ha5u49no)
> 
> I didn't even noticed this parameter, I thought something wrong with the CLAM api, so I wrote my own function to segment the tissue areas, gives me something like this. I guess my code is not as good as the CLAM api. I have wasted too many time on this. ![image](https://private-user-images.githubusercontent.com/1770114/294743979-ac270f49-0d4a-425e-82b8-1915d29f4341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTQxODMsIm5iZiI6MTcwNDYxMzg4MywicGF0aCI6Ii8xNzcwMTE0LzI5NDc0Mzk3OS1hYzI3MGY0OS0wZDRhLTQyNWUtODJiOC0xOTE1ZDI5ZjQzNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDdUMDc1MTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmFlYzM2MjY2MzMxMDdmMjdlNjZmODQ0OTg0MTQ3MTY4MzE0ZDg3NmY1YWNiMDZkOTkyMGNhOWJhYmNkNWJlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PZ0pTSqZQbhLQP6rpe_Cn27Ed4GITJvIZKGEV6-5ev4)
> 
> Another follow-up question: I have noticed that you extract images from 40x magnification with patch size 512 x 512 on cam16 dataset. I'm assuming you will resize the 512x512 to 256x256 before sending to the network to extract patch features . Why not just directly extracting the 256x256 features from 20x magnification like many other works would do? Does extracting patches from 512x512 at 40x mag gives more performance boost?
> 
> Thank you very much, you really help me a lot.

I think this is an agreed and compromised implementation, which has been mentioned several times in the CLAM and TransMIL repository issues. Mainly because level=1 isn't x20 on all slides, and level=0 and level=1 aren't always 2x the difference in length and width. For more details on this check out the CLAM repository issue.

**Comment by weiaicunzai** [comment]
> > > I hope this will address your issue.
> > 
> > 
> > Thanks, guess I have forgot to add `bwh_biopsy.csv` parameters in the command. After adding the `bwh_biopsy.csv` parameter, here is what I got: ![image](https://private-user-images.githubusercontent.com/1770114/294743723-778f36e5-16f6-4061-bcdb-37e6cfdaf6fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTQxODMsIm5iZiI6MTcwNDYxMzg4MywicGF0aCI6Ii8xNzcwMTE0LzI5NDc0MzcyMy03NzhmMzZlNS0xNmY2LTQwNjEtYmNkYi0zN2U2Y2ZkYWY2ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDdUMDc1MTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWI2M2RmMTdiOWM1ZTQyZmQ4ODM0Y2YzMmE4ZGQ4ZmI2MGI5YzM5YmI0YjEzYWY1OGZjYjM0NTI3MzlhMWE5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r3odT6IC_VGenJnSZCtH2Rig0jKE87aLYm4Ha5u49no)
> > I didn't even noticed this parameter, I thought something wrong with the CLAM api, so I wrote my own function to segment the tissue areas, gives me something like this. I guess my code is not as good as the CLAM api. I have wasted too many time on this. ![image](https://private-user-images.githubusercontent.com/1770114/294743979-ac270f49-0d4a-425e-82b8-1915d29f4341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTQxODMsIm5iZiI6MTcwNDYxMzg4MywicGF0aCI6Ii8xNzcwMTE0LzI5NDc0Mzk3OS1hYzI3MGY0OS0wZDRhLTQyNWUtODJiOC0xOTE1ZDI5ZjQzNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDdUMDc1MTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmFlYzM2MjY2MzMxMDdmMjdlNjZmODQ0OTg0MTQ3MTY4MzE0ZDg3NmY1YWNiMDZkOTkyMGNhOWJhYmNkNWJlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PZ0pTSqZQbhLQP6rpe_Cn27Ed4GITJvIZKGEV6-5ev4)
> > Another follow-up question: I have noticed that you extract images from 40x magnification with patch size 512 x 512 on cam16 dataset. I'm assuming you will resize the 512x512 to 256x256 before sending to the network to extract patch features . Why not just directly extracting the 256x256 features from 20x magnification like many other works would do? Does extracting patches from 512x512 at 40x mag gives more performance boost?
> > Thank you very much, you really help me a lot.
> 
> I think this is an agreed and compromised implementation, which has been mentioned several times in the CLAM and TransMIL repository issues. Mainly because level=1 isn't x20 on all slides, and level=0 and level=1 aren't always 2x the difference in length and width. For more details on this check out the CLAM repository issue.

Yes, I have checked the CLAM repository [issue](https://github.com/mahmoodlab/HIPT/blob/a9b5bb8d159684fc4c2c497d68950ab915caeb7e/2-Weakly-Supervised-Subtyping/dataset_csv/tcga_brca_subset.csv.zip) and the [HIPT issue](https://github.com/mahmoodlab/HIPT/blob/master/2-Weakly-Supervised-Subtyping/splits/10foldcv_subtype/tcga_brca/splits_0_bool.csv).  Some slides in TCGA database only have 20x magnification. 
My point is, for slides with only 40x magnification,  extract patches with size 512x512 is fine, we can resize the patch size to 256x256 to obtain the 20x magnification later. However, for slides with only 20x magnification,   extract patches with size 512x512 would cause the number of extracted patches 4 times less than extracting patch size with 256x256.  Will the number of patches extracted per slide affect the overall performance? I wrote a simple function to check if the slide  level 0 is 20x or 40x, then apply the different extracting patch_size (40x use 512, 20x use 256 ) to different slides,  it is necessary?

**Comment by weiaicunzai** [comment]
And I use this to check the mag level 0 of  a slide, is there something wrong ?
`
    if 'aperio.AppMag' in wsi.properties.keys():
        level_0_magnification = int(float(wsi.properties['aperio.AppMag']))
    elif 'openslide.mpp-x' in wsi.properties.keys():
        level_0_magnification = 40 if int(float(wsi.properties['openslide.mpp-x']) * 10) == 2 else 20
    else:
        if max(wsi.level_dimensions[0]) < 50000:
            level_0_magnification =  20
        else:
            level_0_magnification = 40
`

**Comment by DearCaat** [comment]
> And I use this code snippet I used to check the mag level 0 of a slide. Is there something wrong with my code?
> 
> ```python
>     if 'aperio.AppMag' in wsi.properties.keys():
>         level_0_magnification = int(float(wsi.properties['aperio.AppMag']))
>     elif 'openslide.mpp-x' in wsi.properties.keys():
>         level_0_magnification = 40 if int(float(wsi.properties['openslide.mpp-x']) * 10) == 2 else 20
>     else:
>         if max(wsi.level_dimensions[0]) < 50000:
>             level_0_magnification =  20
>         else:
>             level_0_magnification = 40
> ```
I think this might be a more effective way, and it is worth trying. But in my previous work and papers, I only used a simple strategy of using level-0 and then downsampling. As for the correctness of your code, I cannot judge whether it is correct in pathology, because I do not have professional pathology knowledge, such as whether the value of “50000” is appropriate.

**Comment by weiaicunzai** [comment]
> > And I use this code snippet I used to check the mag level 0 of a slide. Is there something wrong with my code?
> > ```python
> >     if 'aperio.AppMag' in wsi.properties.keys():
> >         level_0_magnification = int(float(wsi.properties['aperio.AppMag']))
> >     elif 'openslide.mpp-x' in wsi.properties.keys():
> >         level_0_magnification = 40 if int(float(wsi.properties['openslide.mpp-x']) * 10) == 2 else 20
> >     else:
> >         if max(wsi.level_dimensions[0]) < 50000:
> >             level_0_magnification =  20
> >         else:
> >             level_0_magnification = 40
> > ```
> 
> I think this might be a more effective way, and it is worth trying. But in my previous work and papers, I only used a simple strategy of using level-0 and then downsampling. As for the correctness of your code, I cannot judge whether it is correct in pathology, because I do not have professional pathology knowledge, such as whether the value of “50000” is appropriate.

Thanks, I noticed that the TCGA BRAC dataset, some slides are missing magnification information. So, I looked up other slides contains the magnification information, found out that slides with 40x mag often have larger resolution than 50000 at level 0.  Therefore, 5000 is just an empirical value.
