### ISSUE TITLE
Filenames of TCGA Lung Cancer 

### ISSUE THREAD

**Issue by weiaicunzai** [DearCaat/MHIM-MIL#6]
Thanks for your great work, sorry to bother you. Since you have uploaded the filenames and the labels of  [CAM16 dataset](https://github.com/DearCaat/MHIM-MIL/blob/master/label.csv), could you also please upload the TCGA Lung Cancer filenames and corresponding labels you have used?
Thanks in advance.

**Comment by DearCaat** [comment]
Thank you for your attention to my work, I am happy to answer these questions and discuss the details. 
As for the TCGA-NSCLC dataset, it is used to sub-type [TCGA-LUAD](https://portal.gdc.cancer.gov/projects/TCGA-LUAD) and [TCGA-LUSC](https://portal.gdc.cancer.gov/projects/TCGA-LUSC). These two are sub-projects in TCGA, you only need to download the data of these two sub-projects, and the images of each sub-project are separate. Therefore, I think it may not need a label file.

**Comment by weiaicunzai** [comment]
> Thank you for your attention to my work, I am happy to answer these questions and discuss the details. As for the TCGA-NSCLC dataset, it is used to sub-type [TCGA-LUAD](https://portal.gdc.cancer.gov/projects/TCGA-LUAD) and [TCGA-LUSC](https://portal.gdc.cancer.gov/projects/TCGA-LUSC). These two are sub-projects in TCGA, you only need to download the data of these two sub-projects, and the images of each sub-project are separate. Therefore, I think it may not need a label file.

Thanks, but if I'm correct, the case number and slide number is different from the paper . I'm guessing its due to the consistent updating of this project? 
For example, the case number and slide number of TCGA-LUAD dataset is 512 and 1067, different from the number you have stated in the paper, and I quote: " There are diagnostic slides, LUAD with 541 slides from 478 cases," from your paper.

![image](https://github.com/DearCaat/MHIM-MIL/assets/1770114/d5e0fe3d-21d4-4f22-a4f6-aadf245a41b6)

**Comment by weiaicunzai** [comment]
Sorry, should I use the Diagnostic Slide instead?

**Comment by DearCaat** [comment]
> Thank you for your attention to my work, I am happy to answer these questions and discuss the details. As for the TCGA-NSCLC dataset, it is used to sub-type [TCGA-LUAD](https://portal.gdc.cancer.gov/projects/TCGA-LUAD) and [TCGA-LUSC](https://portal.gdc.cancer.gov/projects/TCGA-LUSC). These two are sub-projects in TCGA, you only need to download the data of these two sub-projects, and the images of each sub-project are separate. Therefore, I think it may not need a label file.

I have upload the TCGA-NSCLC label file. See [file](https://github.com/DearCaat/MHIM-MIL/blob/master/label_tcga_nsclc.csv).
