### ISSUE TITLE
How to evaluation for testing datasets?

### ISSUE THREAD

**Issue by YAOSL98** [DearCaat/MHIM-MIL#7]

**Comment by DearCaat** [comment]
For Camelyon-16 and TCGA-NSCLC, we all used multi-fold cross-validation. Therefore, we didn't use the official Camelyon-16 test set.
- Cross-validation code: `cv-fold=3` for Camelyon-16, `cv-fold=4` for TCGA-NSCLC. [Complete Codes](https://github.com/DearCaat/MHIM-MIL?tab=readme-ov-file#training-mhim-mil).
- If u wanto evaluate for test set by yourself, u should train a model only with train set, and evaluate it with test set. This repo does not contain this codes. u can use the [model api](https://github.com/DearCaat/MHIM-MIL/blob/master/modules/mhim.py).

**Comment by YAOSL98** [comment]
> For Camelyon-16 and TCGA-NSCLC, we all used multi-fold cross-validation. Therefore, we didn't use the official Camelyon-16 test set to evaluate the models.
> 
> * Cross-validation code: `cv-fold=3` for Camelyon-16, `cv-fold=4` for TCGA-NSCLC. [Complete Codes](https://github.com/DearCaat/MHIM-MIL?tab=readme-ov-file#training-mhim-mil).
> * If u wanto evaluate for test set by yourself, u should train a model only with train set, and evaluate it with test set. This repo does not contain this codes. u can use the [model api](https://github.com/DearCaat/MHIM-MIL/blob/master/modules/mhim.py).

Thanks a lot :)
