### ISSUE TITLE
val_ratio setting for c16 dataset

### ISSUE THREAD

**Issue by lingxitong** [DearCaat/MHIM-MIL#8]
hello，nice work,the val_ratio for c16 is 0 and for tcga is 0.13，right？ thanks

**Comment by DearCaat** [comment]
Thanks for your attention.
You're right! This is [complete code](https://github.com/DearCaat/MHIM-MIL?tab=readme-ov-file#abmil). (the number of slides in C16 is too small...)

**Comment by lingxitong** [comment]
thanks for your quick reply，good luck
