### ISSUE TITLE
split question

### ISSUE THREAD

**Issue by lingxitong** [DearCaat/MHIM-MIL#9]
hello，nice work,I have a question,for tcga dataset,slide and case are not one2one,so the 65:10:25 is split according to the slide or the case?wheather we need ensure the slides from same case not appear in different dataset(train val test)?

**Comment by DearCaat** [comment]
thanks for attention.
Split of TCGA is according to the case, following TransMIL and DTFD-MIL.
the [label.csv](https://github.com/DearCaat/MHIM-MIL/blob/master/label_tcga_nsclc.csv) of TCGA is the case id not the slide id, so i can ensure the slides from same case not appear in different dataset. [code of split dataset](https://github.com/DearCaat/MHIM-MIL/blob/master/main.py#L44), [codes of load slide features](https://github.com/DearCaat/MHIM-MIL/blob/master/dataloader.py#L130)

**Comment by lingxitong** [comment]
thanks for your quick reply!

**Comment by akidway** [comment]
> thanks for attention. Split of TCGA is according to the case, following TransMIL and DTFD-MIL. the [label.csv](https://github.com/DearCaat/MHIM-MIL/blob/master/label_tcga_nsclc.csv) of TCGA is the case id not the slide id, so i can ensure the slides from same case not appear in different dataset. [code of split dataset](https://github.com/DearCaat/MHIM-MIL/blob/master/main.py#L44), [codes of load slide features](https://github.com/DearCaat/MHIM-MIL/blob/master/dataloader.py#L130)

Hi, @DearCaat 
The split ratio is 65:10:25 at the case level. Is this the same ratio used at the file level, or is the file level ratio not taken into consideration?

**Comment by DearCaat** [comment]
Hi, @akidway 
The file ratio is not taken into consideration. Some cases have only one file, but some have more.

**Comment by akidway** [comment]
Got it.
Thank you for quick reply!
